config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  root to: 'pages#home'
  get "profile", to: "pages#profile"
  resources :experiences, only: [:show, :new, :create, :index, :destroy] do
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :experience_users, only: [:create]
  end
  resources :experience_users, only: [:index, :destroy]
  resources :users, only: [:show]
  end

app/views/shared/_avatar.html.erb
<% if current_user.facebook_picture_url %>
  <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
  <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <% else %>
  <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logo/logo.png', alt: 'icon', width: "200px"%>
 <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-main">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "All experiences", experiences_path, class: "nav-link" %>
          </li>
           <li class="nav-item" >
            <%= link_to "Create experience", new_experience_path,  class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Favourites", experience_users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.facebook_picture_url %>
            <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
            <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" >
            <%= link_to "Home", root_path,  class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All experiences", experiences_path, class: "nav-link" %>
          </li>
          <li class="nav-item" >
            <%= link_to "Create experience", new_experience_path,  class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path,  class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>