config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  root to: 'pages#home'
  get "profile", to: "pages#profile"
  resources :experiences, only: [:show, :new, :create, :index, :destroy] do
    resources :chatrooms, only: [:show] do
      resources :messages, only: :create
    end
    resources :experience_users, only: [:create]
  end
  resources :experience_users, only: [:index, :destroy]
  resources :users, only: [:show]
  end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :experience_users, dependent: :destroy
  has_one :chatroom, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :address, :event_type, presence: true
  # validates :busyness, inclusion: { in: %w(busy semi-busy empty),
  # message: "%{value} is not a valid busyness" }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address_and_event_type,
    against: [ :name, :address, :event_type ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :experience_users_all, only: [:show]
  # before_action :find_user, only: [:show]


def index

  if params[:query].present?
    @experiences = Experience.search_by_name_and_address_and_event_type(params[:query])
  else
    @experiences = Experience.all
  end

  @markers = @experiences.geocoded.map do |experience|
    {
      lat: experience.latitude,
      lng: experience.longitude,
      info_window: render_to_string(partial: "info_window", locals: { experience: experience }),
    }
  end

end

def show
  @experience = Experience.find(params[:id])
  @chatroom = @experience.chatroom
  @message = Message.new
  @favorite = ExperienceUser.find_by(user: current_user, experience: @experience)
end

def new
  @experience = Experience.new
end

def create
  @experience = Experience.new(experience_params)
  @experience.user = current_user
  @experience.save
  chatroom = Chatroom.create(name: "#{@experience.name}-chatroom")
  @experience.chatroom = chatroom
  redirect_to experiences_path
end

def destroy
    @experience = Experience.find(params[:id])
    @experience.user = current_user
    @experience.destroy
    redirect_to experiences_path
end

private

def find_user
  @user = User.find(params[:id])
end

def experience_users_all
  @experience_users = ExperienceUser.all
end

def experience_params
  params.require(:experience).permit(:name, :address, :busyness, :event_type, :photo)
end
end

app/views/experiences/_info_window.html.erb
 <% if experience.photo.attached? %>
<%= cl_image_tag experience.photo.key, crop: :fill %>
<% end %>
<h2><%= experience.name %></h2>
<p><%= experience.address %></p>

app/views/experiences/_list.html.erb
<div data-search-experiences-target="list">
  <ul>
    <% experiences.each do |experience| %>
      <li><%= link_to experience.name, experience_path(experience) %></li>
    <% end %>
  </ul>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div class="row justify-content-center gy-3">
      <div class="search-bar">
        <%= form_tag experiences_path, autocomplete: "off", method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a venue or an address"%>
      <% end %>
    </div>


    <div class="index-left-map-right">
      <div class="container experiences">
        <div class="row gy-3">
          <% @experiences.each do |experience| %>
            <%= link_to experience_path(experience) do%>
              <div class="col col-12 gap-3 experience-card">
              <% if experience.photo.attached? %>
                <%= cl_image_tag experience.photo.key, height: 150, width: 200, crop: :fill%>
                <% end%>
                <div class="experience-name-and-address">
                <h2><%= experience.name %></h2>
                <p><%= experience.event_type %></p>
                <p class="text-red"><%= "Connect with guests!" %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <div class="map-right" style="width: 100%"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    </div>
</div>
</div>

app/views/experiences/new.html.erb
<div class="container">
  <div class="row justify-content-center gy-3">
      <div class="col col-12 createcard">
        <%= simple_form_for [@experience] do |f| %>
          <%= f.input :name, input_html: { autocomplete: 'off' } %>
          <%= f.input :event_type, collection: ["Bar", "Restaurant", "Cafe", "Club"] %>
          <%= f.input :address,
              input_html: { data: { geocoder_target: "address" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: "btn btn-create"%>
        <% end %>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<div class = "show-banner" style="background-image: url('<%= cl_image_path @experience.photo.key, crop: :fill %>');">
  <div class = "container banner-image" style="height: 100%;">
    <div class = "show-banner-content">
      <h1><%= @experience.name %> </h1>
      <h3> <%= @experience.address%> </h3>
    </div>
  </div>
    <div class = "icon-container">
    <% if @experience.event_type == "bar" %>
        <i class="fas fa-glass-martini-alt"></i>
      <% elsif @experience.event_type == "restaurant" %>
        <i class="fas fa-utensils"></i>
      <% elsif @experience.event_type == "cafe" %>
        <i class="fa fa-coffee"></i>
      <% elsif @experience.event_type == "club" %>
        <i class="fas fa-volume-up"></i>
    <% end %>
        <p style="font-size: smaller"><%= @experience.event_type %></p>
    </div>
    <div class="btn-bookmark" data-controller="disable-button"
                              data-action="click->disable-button#disableheart">
        <% if @favorite %>
          <%= link_to experience_user_path(@favorite), method: :delete do %>
            <div class="d-flex align-items-center">
              <div><i id="icon" class="fas fa-heart" style="color:red"></i></div>
            </div>
          <% end %>
        <% else %>
          <%= link_to experience_experience_users_path(@experience),class: "", method: :post do %>
            <div class="d-flex align-items-center">
              <div><i id="icon" class="far fa-heart"></i></div>
            </div>
          <% end %>
      <% end %>

    </div>
</div>

<div class="container d-flex justify-content-center">
<div class="col-md-8 col-xs-12 col-md-offset-2">
  <div class="panel" id="chat">
    <div class="panel-body"
      data-controller="chatroom-subscription"
      data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
    >
      <h1 class="hidden"
      data-chatroom-subscription-target="current">
      <%= current_user.email %></h1>
      <div class="messages chat-body"
        data-chatroom-subscription-target="messages">
        <% @experience.chatroom.messages.each do |message| %>
          <%= render "messages/message", message: message %>
        <% end %>
    </div>
      <div class="message">
        <%= simple_form_for [@chatroom, @message],
          remote: true,
          url: experience_chatroom_messages_path(@experience, @chatroom),
          method: :post,
          html: {data: {chatroom_subscription_target: "form"}, class: "d-flex"} do |f|
        %>
          <%= f.input :content,
            label: false,
            input_html: { autocomplete: 'off' },
            placeholder: "Message ##{@chatroom.name}",
            wrapper_html: {class: "text-message"}
          %>
          <%= f.submit "Send", class: "btn btn-red"%>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>